version: '3'
services:
    master:
        image: jenkins/jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins-home:/var/jenkins_home
            - jenkins-log:/var/log/jenkins
        networks:
            - jenkins-net
        restart: always
    proxy:
        image: thoreaudesign/jenkins-docker-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            jenkins-net:
                aliases:
                    - proxy1
        restart: always
volumes:
    jenkins-home:
    jenkins-log:
networks:
    jenkins-net:
